name: analisador_sintatico
description: Analisador Sintático

publish_to: none
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  csv: 5.0.1
  analisador_lexico:
    path: ../T1-OtavioPontes-20221

dev_dependencies:
  analyzer: 4.1.0
  equatable: 2.0.3
  dartz: 0.10.1

scripts:
  run: dart lib/src/main.dart
